spring:
  application:
    name: testTask
  datasource:
    url: jdbc:postgresql://localhost:5432/taskDB
    username: usr
    password: pwd
  flyway:
    enabled: true
    user: usr
    password: pwd
    url: jdbc:postgresql://localhost:5432/taskDB

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE